### ISSUE TITLE
Build with wasm-pack for example fails on MacOS

### ISSUE THREAD

**Issue by andynog** [forbole/cosmos-rust-wallet#16]
Trying to follow the instructions in the examples folder and when I try to run the wasm-pack command it's not working.

Environment: 
`macOS Catalina 10.15.7`

I have Rust installed
```
(~/dev/github.com/forbole/cosmos-rust-wallet) $> rustc -V
rustc 1.52.1 (9bc8c42bb 2021-05-09)
```

Also installed wasm-pack
```
(~/dev/github.com/forbole/cosmos-rust-wallet) $> curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
info: downloading wasm-pack
info: successfully installed wasm-pack to `$HOME/.cargo/bin/wasm-pack`

(~/dev/github.com/forbole/cosmos-rust-wallet) $> wasm-pack  -V
wasm-pack 0.9.1
```

But when I run the command `wasm-pack` it fails with the error below (note: the instruction said to run from the crw-wallet but I believe repo name has changed to cosmos-rust-wallet)
```
(~/dev/github.com/forbole/cosmos-rust-wallet) $> wasm-pack build --release -- --features wasm-bindgen
Error: failed to parse manifest: $HOME/dev/github.com/forbole/cosmos-rust-wallet/Cargo.toml
Caused by: missing field `package`
```

Am I doing something wrong ?

**Comment by bragaz** [comment]
Hi @andynog. It's a macOS related problem, see here: https://github.com/forbole/cosmos-rust-wallet/issues/9

**Comment by andynog** [comment]
Ok @bragaz I will try that from a Linux machine

**Comment by manu0466** [comment]
@andynog You can use the docker container to compile the package from macOS.
From within the crw-wallet dir you can run `make build-wasm` or if you don't have make you can run `docker run -u $(id -u):$(id -g) --rm -v $(pwd):/workdir forbole/wasm-rust-builder:1.52.1 wasm-pack build --release -- --features wasm-bindgen`.
Let me know if this works out for you.

**Comment by andynog** [comment]
Thanks @manu0466 I could compile directly on Linux and via Docker on MacOS and test the example. Both worked! I will close this issue.
