### ISSUE TITLE
 copy-webpack-plugin plugin config error

### ISSUE THREAD

**Issue by fragilegirl** [forbole/cosmos-rust-wallet#81]
[webpack-cli] Failed to load '/home/ellie/cosmos-rust-wallet/examples/browser/webpack.config.js' config
[webpack-cli] Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options[0] should be an object:
   object { patterns, options? } 
seems to be a new schema change here are the relevant links to the issues and possible solutions I don't know that much js so I can't fix this 
https://stackoverflow.com/a/62680933
https://webpack.js.org/plugins/copy-webpack-plugin/#options-1

**Comment by manu0466** [comment]
This issue is occurring only on your fork, see the comment on PR #79 on how to fix it.
